name: CI
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn lint
    - name: Run TSC
      run: yarn tsc
    - name: Run Prettier
      run: yarn format --check
